# Generated by Django 4.2.2 on 2023-06-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="logo",
            field=models.ImageField(upload_to="events_logos"),
        ),
    ]
